[package]
name = "ruw"
version = "0.0.1"
edition = "2021"
rust-version = "1.75"

[dependencies]
futures-core = "0.3.30"
pin-project = "1"

[dev-dependencies]
async-std = { version = "1.12.0", features = ["attributes"] }
